apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      kind: Application
      name: gitlab-privileged-runner
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: gitlab-privileged-runner
        namespace: argocd
      $patch: delete

  - target:
      group: argoproj.io
      kind: Application
      name: gitlab-runner
    patch: |-
      - op: remove
        path: /spec/source/helm/valuesObject/runners/cache/secretName
  - target:
      group: argoproj.io
      kind: Application
      name: gitlab-runner
    patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/metrics/enabled
        value: false
  - target:
      group: argoproj.io
      kind: Application
      name: gitlab-runner
    patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/runners/config
        value: |-
          [[runners]]
            limit = 3
            name = "kubernetes-runner"
            
            [runners.kubernetes]
              allowed_pull_policies = ["always", "if-not-present"]
              pull_policy = "if-not-present"
              image = "alpine:latest"
            [runners.kubernetes.volumes]
            [[runners.kubernetes.volumes.secret]]
              name = "homelab-ca"
              mount_path = "/usr/local/share/ca-certificates"
              read_only = true
