apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ./resources/cilium-l2-announcement-policy.yaml
  - ./resources/cilium-load-balancer-ip-pool.yaml
  - ./resources/gateway-api.yaml
