apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespace.yaml
  - ./resources/ca-selfsigned-issuer.yaml
  - ./resources/ca-certificate.yaml
  - ./resources/ca-issuer.yaml
  - ./resources/certificate.yaml
  - ./resources/configmap.yaml
  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/network-policy.yaml
  - ./resources/ca-bundle.yaml
  - ./resources/external-secret.yaml
