version: 2
updates:
  # Monitor Docker images in manifests
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "kallepan"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
