apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-s3-connection
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection.yml: |
          provider: AWS
          region: eu-west-1
          aws_access_key_id: {{ .s3_access_key }}
          aws_secret_access_key: {{ .s3_secret_key }}
          aws_signature_version: 4
          host: s3.storage.home.arpa
          endpoint: https://s3.storage.home.arpa
          path_style: true
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_ACCESS_KEY
    - secretKey: s3_secret_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-secrets
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-registry-minio-connection
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        registry.s3.yml: |
          s3:
            bucket: gitlab-registry-storage
            accesskey: {{ .s3_access_key }}
            secretkey: {{ .s3_secret_key }}
            region: eu-west-1
            v4auth: true
            regionendpoint: https://s3.storage.home.arpa
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_ACCESS_KEY
    - secretKey: s3_secret_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-keycloak-omniauth
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-keycloak-omniauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        omniauth.yml: |
          name: openid_connect
          label: Keycloak OpenID Connect
          args:
            name: openid_connect
            scope:
              - openid
              - email
              - profile
            response_type: code
            issuer: https://sso.svc.home.arpa/realms/homelab
            client_auth_method: query
            discovery: true
            uid_field: preferred_username
            pkce: true
            client_options:
              identifier: {{ .client_id }}
              secret: {{ .client_secret }}
              redirect_uri: https://gitlab.svc.home.arpa/users/auth/openid_connect/callback
  data:
    - secretKey: client_id
      remoteRef:
        key: services/gitlab
        property: GITLAB_OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: services/gitlab
        property: GITLAB_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-backups-creds
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-backups-minio-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          [default]
          access_key = {{ .s3_access_key }}
          access_token = 
          add_encoding_exts = 
          add_headers = 
          bucket_location = EU
          ca_certs_file = 
          cache_file = 
          check_ssl_certificate = True
          check_ssl_hostname = True
          cloudfront_host = cloudfront.amazonaws.com
          connection_max_age = 5
          connection_pooling = True
          content_disposition = 
          content_type = 
          default_mime_type = binary/octet-stream
          delay_updates = False
          delete_after = False
          delete_after_fetch = False
          delete_removed = False
          dry_run = False
          enable_multipart = True
          encoding = UTF-8
          encrypt = False
          expiry_date = 
          expiry_days = 
          expiry_prefix = 
          follow_symlinks = False
          force = False
          get_continue = False
          gpg_command = None
          gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
          gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
          gpg_passphrase = 
          guess_mime_type = True
          host_base = s3.storage.home.arpa
          host_bucket = %(bucket).s3.storage.home.arpa
          human_readable_sizes = False
          invalidate_default_index_on_cf = False
          invalidate_default_index_root_on_cf = True
          invalidate_on_cf = False
          keep_dirs = False
          kms_key = 
          limit = -1
          limitrate = 0
          list_allow_unordered = False
          list_md5 = False
          log_target_prefix = 
          long_listing = False
          max_delete = -1
          max_retries = 5
          mime_type = 
          multipart_chunk_size_mb = 15
          multipart_copy_chunk_size_mb = 1024
          multipart_max_chunks = 10000
          preserve_attrs = True
          progress_meter = True
          proxy_host = 
          proxy_port = 0
          public_url_use_https = False
          put_continue = False
          recursive = False
          recv_chunk = 65536
          reduced_redundancy = False
          requester_pays = False
          restore_days = 1
          restore_priority = Standard
          secret_key = {{ .s3_secret_key }}
          send_chunk = 65536
          server_side_encryption = False
          signature_v2 = False
          signurl_use_https = False
          simpledb_host = sdb.amazonaws.com
          skip_destination_validation = False
          skip_existing = False
          socket_timeout = 300
          ssl_client_cert_file = 
          ssl_client_key_file = 
          stats = False
          stop_on_error = False
          storage_class = 
          throttle_max = 100
          upload_id = 
          urlencoding_mode = normal
          use_http_expect = False
          use_https = True
          use_mime_magic = True
          verbosity = WARNING
          website_endpoint = https://%(bucket).s3.storage.home.arpa/
          website_error = 
          website_index = index.html
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_ACCESS_KEY
    - secretKey: s3_secret_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_SECRET_ACCESS_KEY
