apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: gitlab-postgresql
  namespace: gitlab
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: gitlab-postgresql
      cnpg.io/podRole: instance
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: gitlab-registry-postgresql
  namespace: gitlab
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: gitlab-registry-postgresql
      cnpg.io/podRole: instance
