apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./cert.yaml
  - ./datasources.yaml
  - ./gateway.yaml
  - ./grafana.yaml
  - ./operator.yaml
  - ./virtual-service.yaml
