apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtual-service-grafana
spec:
  hosts:
    - grafana.svc.home.arpa
  gateways:
    - gateway-grafana
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana-service.observability.svc.cluster.local
            port:
              number: 3000
