apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls
  namespace: istio-system
spec:
  secretName: pgadmin-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pgadmin.svc.home.arpa
