apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/certificate.yaml
  - ./resources/external-secret-postgres.yaml
  - ./resources/external-secret.yaml
  - ./resources/cluster.yaml
  - ./resources/valkey.yaml
  - ./resources/gitlab.yaml
  - ./resources/http-route.yaml
  - ./resources/tcp-route.yaml
