apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/application-cluster.yaml
  - ./resources/application-operator.yaml
  - ./resources/deployment.yaml
  - ./resources/destination-rule.yaml
  - ./resources/http-route.yaml
  - ./resources/namespace.yaml
