{
 "title": "Istio Performance Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance Dashboard Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Dashboard README",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "The charts on this dashboard are intended to show Istio main components cost in terms of resources utilization under steady load.\n\n- **vCPU / 1k rps:** shows vCPU utilization by the main Istio components normalized by 1000 requests/second. When idle or low traffic, this chart will be blank. The curve for istio-proxy refers to the services sidecars only.\n- **vCPU:** vCPU utilization by Istio components, not normalized.\n- **Memory:** memory footprint for the components. Telemetry and policy are normalized by 1k rps, and no data is shown  when there is no traffic. For ingress and istio-proxy, the data is per instance.\n- **Bytes transferred / sec:** shows the number of bytes flowing through each Istio component.\n\n\n"
   }
  },
  {
   "title": "vCPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU / 1k rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m])) / (round(sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m])), 0.001)/1000))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"istio-system\",container=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Memory and Data Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"istio-ingressgateway-.*\"}) / count(container_memory_working_set_bytes{pod=~\"istio-ingressgateway-.*\",container!=\"POD\"})",
     "legendFormat": "per istio-ingressgateway"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace!=\"istio-system\",container=\"istio-proxy\"}) / count(container_memory_working_set_bytes{namespace!=\"istio-system\",container=\"istio-proxy\"})",
     "legendFormat": "per istio proxy"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_request_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Istio Component Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Istiod Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"istiod\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{app=\"istiod\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{app=\"istiod\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}[1m])) by (container)",
     "legendFormat": "{{ container }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{app=\"istiod\"}[1m])",
     "legendFormat": "pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{ container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{app=\"istiod\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  }
 ]
}
{
 "title": "Istio Control Plane Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Deployed Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pilot Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tag) (istio_build{component=\"pilot\"})",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"discovery\",pod=~\"istiod-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_stack_inuse_bytes{app=\"istiod\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_inuse_bytes{app=\"istiod\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{app=\"istiod\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memstats_alloc_bytes_total{app=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memstats_mallocs_total{app=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"discovery\",pod=~\"istiod-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutines{app=\"istiod\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Push Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "XDS Pushes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (irate(pilot_xds_pushes[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (type,event) (rate(pilot_k8s_reg_events[$__rate_interval]))",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type,event) (rate(pilot_k8s_cfg_events[$__rate_interval]))",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type) (rate(pilot_push_triggers[$__rate_interval]))",
     "legendFormat": "Push {{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Total number of XDS connections\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
     "legendFormat": "Connections (client reported)"
    },
    { "expr": "sum (pilot_xds)", "legendFormat": "Connections (server reported)" }
   ]
  },
  {
   "title": "Push Errors",
   "type": "timeseries",
   "description": "Number of push errors. Many of these are at least potentional fatal and should be explored in-depth via Istiod logs.\nNote: metrics here do not use rate() to avoid missing transition from \"No series\"; series are not reported if there are no errors at all.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (type) (pilot_total_xds_rejects)",
     "legendFormat": "Rejected Config ({{type}})"
    },
    {
     "expr": "pilot_total_xds_internal_errors",
     "legendFormat": "Internal Errors"
    },
    { "expr": "pilot_xds_push_context_errors", "legendFormat": "Push Context Errors" }
   ]
  },
  {
   "title": "Push Time",
   "type": "heatmap",
   "description": "Count of active and pending proxies managed by each instance.\nPending is expected to converge to zero.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_push_time_bucket{}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Push Size",
   "type": "heatmap",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_config_size_bytes_bucket{}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Validation",
   "type": "timeseries",
   "description": "Rate of XDS push operations, by type. This is incremented on a per-proxy basis.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum (rate(galley_validation_passed[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (rate(galley_validation_failed[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Injection",
   "type": "timeseries",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum (rate(sidecar_injection_success_total[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (rate(sidecar_injection_failure_total[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}
{
 "title": "Istio Ztunnel Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ztunnel Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tag) (istio_build{component=\"ztunnel\"})",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"istio-proxy\",pod=~\"ztunnel-.*\"})",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"istio-proxy\",pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Connections opened and closed per instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_tcp_connections_opened_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Opened ({{pod}})"
    },
    {
     "expr": "-sum by (pod) (rate(istio_tcp_connections_closed_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Closed ({{pod}})"
    }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "timeseries",
   "description": "Bytes sent and received per instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_tcp_sent_bytes_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Sent ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(istio_tcp_received_bytes_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Received ({{pod}})"
    }
   ]
  },
  {
   "title": "DNS Request",
   "type": "timeseries",
   "description": "DNS queries received per instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_dns_requests_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Request ({{pod}})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "XDS Connections",
   "type": "timeseries",
   "description": "Count of XDS connection terminations.\nThis will typically spike every 30min for each instance.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_xds_connection_terminations_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "XDS Connection Terminations ({{pod}})"
    }
   ]
  },
  {
   "title": "XDS Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (url) (irate(istio_xds_message_total{pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Workload Manager",
   "type": "timeseries",
   "description": "Count of active and pending proxies managed by each instance.\nPending is expected to converge to zero.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (workload_manager_active_proxy_count{pod=~\"ztunnel-.*\"})",
     "legendFormat": "Active Proxies ({{pod}})"
    },
    {
     "expr": "sum by (pod) (workload_manager_pending_proxy_count{pod=~\"ztunnel-.*\"})",
     "legendFormat": "Pending Proxies ({{pod}})"
    }
   ]
  }
 ]
}
{
 "title": "Istio Wasm Extension Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Wasm VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_null_active)",
     "legendFormat": "native"
    },
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_v8_active)",
     "legendFormat": "v8"
    }
   ]
  },
  {
   "title": "Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_null_created)",
     "legendFormat": "native"
    },
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_v8_created)",
     "legendFormat": "v8"
    }
   ]
  },
  {
   "title": "Wasm Module Remote Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Entry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_cache_entries)",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Cache Visit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_cache_hits)",
     "legendFormat": "hits"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_misses)",
     "legendFormat": "misses"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_negative_hits)",
     "legendFormat": "negative hits"
    }
   ]
  },
  {
   "title": "Remote Fetch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_failures)",
     "legendFormat": "failures"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_successes)",
     "legendFormat": "successes"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  }
 ]
}
{
 "title": "Istio Mesh Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Volume",
   "type": "stat",
   "description": "Total requests in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{reporter=~\"source|waypoint\"}[$__rate_interval])), 0.01)"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "description": "Total success rate of requests in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code!~\"5..\"}[$__rate_interval])) / sum (rate(istio_requests_total{reporter=~\"source|waypoint\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "stat",
   "description": "Total 4xx requests in in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code=~\"4..\"}[$__rate_interval])), 0.01)or vector(0)"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "description": "Total 5xx requests in in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code=~\"5..\"}[$__rate_interval])), 0.01)or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP/gRPC Workloads",
   "type": "table",
   "description": "Request information for HTTP services",
   "gridPos": { "h": 16, "w": 24, "y": 10 },
   "targets": [
    {
     "expr": "label_join(sum by (destination_workload,destination_workload_namespace,destination_service) (rate(istio_requests_total{reporter=~\"source|waypoint\"}[$__rate_interval])), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join(histogram_quantile(0.5, sum by (le,destination_workload,destination_workload_namespace) (rate(istio_request_duration_milliseconds_bucket{reporter=~\"source|waypoint\"}[$__rate_interval]))), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join(histogram_quantile(0.9, sum by (le,destination_workload,destination_workload_namespace) (rate(istio_request_duration_milliseconds_bucket{reporter=~\"source|waypoint\"}[$__rate_interval]))), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join(histogram_quantile(0.99, sum by (le,destination_workload,destination_workload_namespace) (rate(istio_request_duration_milliseconds_bucket{reporter=~\"source|waypoint\"}[$__rate_interval]))), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join(sum by (destination_workload,destination_workload_namespace) (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code!~\"5..\"}[$__rate_interval]))/sum by (destination_workload,destination_workload_namespace) (rate(istio_requests_total{reporter=~\"source|waypoint\"}[$__rate_interval])), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "TCP Workloads",
   "type": "table",
   "description": "Bytes sent and recieived information for TCP services",
   "gridPos": { "h": 16, "w": 24, "y": 26 },
   "targets": [
    {
     "expr": "label_join(sum by (destination_workload,destination_workload_namespace,destination_service) (rate(istio_tcp_received_bytes_total{reporter=~\"source|waypoint\"}[$__rate_interval])), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join(sum by (destination_workload,destination_workload_namespace,destination_service) (rate(istio_tcp_sent_bytes_total{reporter=~\"source|waypoint\"}[$__rate_interval])), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    }
   ]
  },
  { "title": "Istio Component Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Istio Component Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (component,tag) (istio_build)",
     "legendFormat": "{{component}} ({{tag}})"
    }
   ]
  }
 ]
}