{
 "title": "Kubernetes Metrics",
 "description": "Kubernetes Metrics",
 "tags": [ "production" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } },
   { "name": "k8s_cluster", "label": "K8s Cluster", "query": "infrastructure,service" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max without(instance,node)(1 - kubelet_volume_stats_available_bytes{namespace=~\"$namespace\",k8s_cluster=~\"$k8s_cluster\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",k8s_cluster=~\"$k8s_cluster\"})",
     "legendFormat": "{{namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Availability (30d) > 99.000%",
   "type": "timeseries",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d",
     "legendFormat": "{{verb}} availability"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio_rate5m", "legendFormat": "__auto" }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttle > 0 by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Per Namespace",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(namespace) (rate(kube_pod_info[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing/Restarting Pods",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts with Reason",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{reason!=\"Completed\"}) by (pod,reason)",
     "legendFormat": "{{pod}}: {{reason}}"
    }
   ]
  },
  {
   "title": "Pod Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\"}) by (pod, namespace,node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (pod,namespace,node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits) by (pod,namespace,node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\",namespace=~\"$namespace\"}) by (pod, namespace,node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests) by (pod,namespace,node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Memory Usage by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{k8s_cluster=~\"$k8s_cluster\"}) by (namespace) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{k8s_cluster=~\"$k8s_cluster\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=~\"idle|iowait\",k8s_cluster=~\"$k8s_cluster\"}[$__rate_interval]) )by (instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{k8s_cluster=~\"$k8s_cluster\"}/node_memory_MemTotal_bytes{k8s_cluster=~\"$k8s_cluster\"}) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Average Network Traffic by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-avg(rate(node_network_receive_bytes_total{k8s_cluster=~\"$k8s_cluster\"}[$__rate_interval])) by(instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "avg (rate(node_network_transmit_bytes_total{k8s_cluster=~\"$k8s_cluster\"}[$__rate_interval])) by (instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1 - sum by(instance)(node_filesystem_avail_bytes{mountpoint=\"/var/mnt/local\",job=\"node-exporter\",fstype!=\"\"}) / \n  sum by(instance)(node_filesystem_size_bytes{mountpoint=\"/var/mnt/local\",job=\"node-exporter\",fstype!=\"\"})\n) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk I/O by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])) by(instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}} read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])) by(instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename)",
     "legendFormat": "{{nodename}} written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"node-exporter\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])) by(instance) * on(instance) group_left(nodename) max(node_uname_info) by(instance,nodename) ",
     "legendFormat": "{{nodename}} io time"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1 + sum(kube_node_status_condition{status=\"false\",condition=\"Ready\"}) by (node) * 100 + sum(kube_node_status_condition{status=\"unknown\"}) by (node) * 100 \n+ sum(kube_node_status_condition{status=~\"true\",condition!~\"EtcdIsVoter|Ready\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Alerts over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!~\"InfoInhibitor|Watchdog\"}) by (alertname)",
     "legendFormat": "{{label_name}}{{namespace}}"
    }
   ]
  },
  {
   "title": "Probes",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 88 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 } },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Istio Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[$__rate_interval])) by(destination_workload) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}