# Backstage TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: istio-system
spec:
  secretName: backstage-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "backstage.svc.home.arpa"
