apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    # Chore: Update the chart version
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/master/CHART_VERSIONS?ref_type=heads
    version: "10.0.1"
    values:
      certmanager:
        install: false
        installCRDs: false
      certmanager-issuer:
        email: kajeepan.kandeepan@gmail.com
      gitlab-runner:
        install: false
      gitlab:
        gitaly:
          persistence:
            enabled: true
            size: 50Gi
            storageClass: ceph-block
        gitlab-shell:
          sshDaemon: gitlab-sshd
          config:
            proxyProtocol: true
            proxyPolicy: "use"
          istio:
            entryPoint: ssh
        kas:
          ingress:
            enabled: false
        toolbox:
          backups:
            cron:
              enabled: true
              schedule: "0 2 * * *"
              persistence:
                enabled: true
                accessMode: ReadWriteOnce
                size: 30Gi
                storageClass: ceph-block
              extraArgs: --skip db
            objectStorage:
              backend: s3
              config:
                # Configure using s3cmd
                secret: gitlab-backups-minio-creds
                key: config
          persistence:
            enabled: true
            size: "10Gi"
            accessMode: ReadWriteOnce
            storageClass: ceph-block
        webservice:
          monitoring:
            ipWhitelist:
              # Kubernetes Cluster IP Range
              - 127.0.0.0/8
              - 10.0.0.0/8
      global:
        appConfig:
          usernameChangingEnabled: false
          object_store:
            enabled: true
            connection:
              secret: gitlab-minio-connection
              key: connection.yml
          artifacts:
            enabled: true
          backups:
            bucket: gitlab-backups
            tmpBucket: gitlab-backups-tmp
          externalDiffs:
            enabled: true
          uploads:
            enabled: true
          lfs:
            enabled: true
          packages:
            enabled: true
          terraformState:
            enabled: true
          ciSecureFiles:
            enabled: true
          dependencyProxy:
            enabled: true
          omniauth:
            enabled: true
            autoSignInWithProvider: openid_connect
            allowSingleSignOn:
              - openid_connect
            blockAutoCreatedUsers: true
            providers:
              - secret: gitlab-keycloak-omniauth
                key: omniauth.yml
          contentSecurityPolicy:
            enabled: true
            report_only: true
          cron_jobs:
            # Flag stuck CI builds as failed
            stuck_ci_jobs_worker:
              cron: "0 * * * *"
            # Schedule pipelines in the near future
            pipeline_schedule_worker:
              cron: "3-59/10 * * * *"
            # Remove expired build artifacts
            expire_build_artifacts_worker:
              cron: "*/7 * * * *"
            # Periodically run 'git fsck' on all repositories.
            repository_check_worker:
              cron: "20 * * * *"
            # Remove outdated repository archives
            repository_archive_cache_worker:
              cron: "0 * * * *"
            # Verify custom GitLab Pages domains
            pages_domain_verification_cron_worker:
              cron: "*/15 * * * *"
            schedule_migrate_external_diffs_worker:
              cron: "15 * * * *"
            # Prune stale group runners on opted-in namespaces
            ci_runners_stale_group_runners_prune_worker_cron:
              cron: "30 * * * *"
            # Periodically update ci_runner_versions table with up-to-date versions and status
            ci_runner_versions_reconciliation_worker:
              cron: "@daily"
            # Periodically clean up stale ci_runner_machines records
            ci_runners_stale_machines_cleanup_worker:
              cron: "36 * * * *"
            ci_click_house_finished_pipelines_sync_worker:
              cron: "*/4 * * * *"
              args: [0, 1]
            # Snapshot active user statistics
            historical_data_worker:
              cron: "0 12 * * *"
            loose_foreign_keys_cleanup_worker_cron:
              cron: "*/5 * * * *"
        certificates:
          customCAs:
            - secret: homelab-ca
              keys:
                - gitlab.svc.home.arpa.crt
        edition: ee
        gitaly:
          enabled: true
        psql:
          host: psql.storage.home.arpa
          port: 5432
          database: gitlab_db
          username: gitlab
          password:
            useSecret: true
            secret: gitlab-postgres-credentials
            key: postgres_password
        redis:
          auth:
            enabled: true
            secret: gitlab-redis-credentials
            key: redis_password
          host: redis.storage.home.arpa
          port: 6379
        hosts:
          domain: svc.home.arpa
          externalIP: 10.10.20.20
          gitlab: {}
          hostSuffix: null
          https: true
          kas: {}
          minio: {}
          pages: {}
          registry: {}
          smartcard: {}
          ssh: ~
          tls: {}
        ingress:
          enabled: false
        kas:
          enabled: true
        minio:
          enabled: false
        monitoring:
          enabled: true
        spamcheck:
          enabled: true
        shell:
          port: 2222
        pages:
          enabled: true
          objectStore:
            enabled: true
            bucket: gitlab-pages
            connection:
              secret: gitlab-minio-connection
              key: connection.yml
        registry:
          enabled: true
        time_zone: Europe/Berlin
      traefik:
        install: false
      prometheus:
        install: true
      registry:
        storage:
          secret: gitlab-registry-minio-connection
          key: registry.s3.yml
        database:
          enabled: true
          host: psql.storage.home.arpa
          port: 5432
          user: gitlab_registry
          name: gitlab_registry_db
          password:
            secret: gitlab-registry-postgres-credentials
            key: postgres_password
          migrations:
            enabled: true
