apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ./resources/certificate.yaml
  - ./resources/gateway.yaml
  - ./resources/keycloak.yaml
  - ./resources/virtual-service.yaml
