apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: https://bao.infra.home.arpa
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: homelab-ca
        namespace: external-secrets
        key: ca.crt
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: bao-access
            namespace: external-secrets
            key: role-id
          secretRef:
            name: bao-access
            namespace: external-secrets
            key: secret-id
