apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-values.yaml
    target:
      kind: Application
      name: argocd

  # On the management cluster, argocd is exposed differently, thus we can patch the certificate, gateway and virtual service to be removed
  - target:
      group: cert-manager.io
      kind: Certificate
      name: argocd-tls
    patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: argocd-tls
      $patch: delete

  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: httproute-argocd
    patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: httproute-argocd
      $patch: delete
