apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-ca
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cert-manager-ca
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .tls_crt }}"
        tls.key: "{{ .tls_key }}"
        ca.crt: "{{ .ca_crt }}"
  data:
    - secretKey: tls_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.crt
    - secretKey: tls_key
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.key
    - secretKey: ca_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: ca.crt
