apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: services/oauth2-proxy
        property: OAUTH2_PROXY_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: services/oauth2-proxy
        property: OAUTH2_PROXY_CLIENT_SECRET
    - secretKey: cookie_secret
      remoteRef:
        key: services/oauth2-proxy
        property: OAUTH2_PROXY_COOKIE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-ca
  namespace: oauth2-proxy
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homelab-ca
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        homelab-ca.crt: "{{ .ca_crt }}"
  data:
    - secretKey: ca_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.crt
