apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./certificate.yaml
  - ./contact-point.yaml
  - ./datasources.yaml
  - ./grafana.yaml
  - ./http-route.yaml
  - ./notification-policy.yaml
