apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/kallepan
      - DockerHub:
        - abbr: DO
          href: https://hub.docker.com/u/kallepan
    - Social:
      - LinkedIn:
        - abbr: LI
          href: https://www.linkedin.com/in/kajeepankandeepan1999/
    - Mail:
      - Gmail:
        - abbr: GM
          href: http://kajeepan.kandeepan@gmail.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Core Infrastructure:
      - Proxmox:
          description: Proxmox Virtual Environment (PVE) for HomeLab.
          href: https://192.168.0.2:8006/
          icon: proxmox.png
      - Rancher:
          description: Rancher Management UI for Kubernetes Clusters.
          href: https://rancher.infra.home.arpa/
          icon: rancher.png
      - Portainer:
          description: Management UI for Docker.
          href: https://portainer.app.home.arpa/
          icon: portainer.png
      - WireGuard:
          description: WireGuard VPN into the HomeLab.
          href: http://192.168.0.10:51820
          icon: wireguard.png
      - Traefik Docker:
          description: Traefik dashboard for Docker.
          href: https://traefik.app.home.arpa/dashboard/#/
          icon: traefik.png
    - Development & DevOps:
      - GitLab:
          description: Fully integrated software development platform.
          href: https://gitlab.svc.home.arpa/users/sign_in?auto_sign_in=false
          icon: gitlab.png
      - Argo CD Infra:
          description: Argo CD for managing Kubernetes applications on infrastructure cluster.
          href: https://argocd.infra.home.arpa/
          icon: argo-cd.png
      - Argo CD Service:
          description: Argo CD for managing Kubernetes applications on service cluster.
          href: https://argocd.svc.home.arpa/
          icon: argo-cd.png
      - Argo Workflows:
          description: Workflow engine for Kubernetes.
          href: https://workflows.svc.home.arpa
          icon: argo-cd.png
      - Sonarqube:
          description: Continuous code quality inspection tool.
          href: https://sonarqube.svc.home.arpa/
          icon: sonarqube.png
    - Monitoring & Observability:
      - Monitoring:
          description: Monitoring instance.
          href: https://grafana.svc.home.arpa/
          icon: grafana.png
      - Prometheus:
          description: Monitoring and alerting toolkit.
          href: https://prometheus.svc.home.arpa/
          icon: prometheus.png
      - Alertmanager:
          description: Alertmanager for Prometheus.
          href: https://alerts.svc.home.arpa/
          icon: alertmanager.png
      - Jaeger:
          description: Distributed tracing system.
          href: https://jaeger.svc.home.arpa/
          icon: jaeger.png
      - Kiali:
          description: Service mesh observability.
          href: https://kiali.svc.home.arpa/
          icon: traefik-proxy.png
      - CAdvisor:
          description: Container resource usage and performance analysis.
          href: https://cadvisor.app.home.arpa/
          icon: cadvisor.png
    - Security & Identity:
      - Keycloak:
          description: Open Source Identity and Access Management.
          href: https://sso.svc.home.arpa/
          icon: keycloak.png
      - Vault:
          description: Secret Storage and Management.
          href: https://openbao.svc.home.arpa/
          icon: vault.png
    - Communication & Collaboration:
      - Mattermost:
          description: Internal chat and collaboration platform.
          href: https://mattermost.svc.home.arpa/
          icon: mattermost.png
      - Documentation:
          description: Internal mkdocs documentation, hosted on backstage.
          href: https://backstage.svc.home.arpa/docs/default/component/homelab-documentation
          icon: mkdocs.png
    - Data & Storage:
      - Garage:
          description: S3 Object Storage.
          href: https://web.storage.home.arpa/
          icon: garage.png
      - PgAdmin:
          description: PostgreSQL Management Tool.
          href: https://pgadmin.app.home.arpa/
          icon: postgres.png
      - Ceph Dashboard:
          description: Ceph Storage Cluster Management.
          href: https://ceph.svc.home.arpa/
          icon: ceph.png
    - Utilities & Tools:
      - It-Tools:
          description: Collection of tools useful for IT professionals.
          href: https://it-tools.svc.home.arpa/
          icon: it-tools.png
      - Kasm:
          description: Containerized workspace platform for remote desktop access. For setup visit https://kasm-admin.app.home.arpa/
          href: https://kasm.app.home.arpa/
          icon: kasm.png
      - Microcks:
          description: Test API endpoints
          href: https://microcks.app.home.arpa/
          icon: microcks.png
      - Backstage:
          description: Backstage Developer Portal.
          href: https://backstage.svc.home.arpa/
          icon: backstage.png
  custom.css: ""
  custom.js: ""
  settings.yaml: |
    title: HomeLab
    base: https://home.infra.home.arpa/
    showStats: false
    theme: dark
    color: slate
    headerStyle: boxed
    quicklaunch:
      searchDescriptions: false
      hideInternetSearch: false
      hideVisitURL: false
    layout:
      Core Infrastructure:
        icon: mdi-server
      Development & DevOps:
        icon: mdi-git
      Monitoring & Observability:
        icon: mdi-chart-line
      Security & Identity:
        icon: mdi-security
      Communication & Collaboration:
        icon: mdi-message
      Data & Storage:
        icon: mdi-database
      Utilities & Tools:
        icon: mdi-tools
  widgets.yaml: |
    - datetime:
        locale: de
        format:
          dateStyle: long
          timeStyle: long
        text_size: x1
    - greeting:
        text_size: xl
        text: Welcome to my HomeLab
  proxmox.yaml: |
    ---
    # url: https://proxmox.host.or.ip:8006
    # token: username@pam!Token ID
    # secret: secret
