apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: registry.svc.home.arpa/organizations/homelab/backstage/main
    newTag: 0.0.3

resources:
  - ./resources/certificate.yaml
  - ./resources/deployment.yaml
  - ./resources/namespace.yaml
  - ./resources/service.yaml
  - ./resources/configmap.yaml
  - ./resources/virtual-service.yaml
