apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway-mattermost
  namespace: mattermost
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - mattermost.svc.home.arpa
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: mattermost-tls
      hosts:
        - mattermost.svc.home.arpa
