apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gitlab-runner
    repoURL: https://charts.gitlab.io
    targetRevision: 0.*.*
    helm:
      releaseName: gitlab-runner
      valuesObject:
        concurrent: 3
        extraEnv:
          # Ensure CA certificate is used by the runner cache.
          AWS_CA_BUNDLE: /home/gitlab-runner/.gitlab-runner/certs/ca.crt
        service:
          enabled: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
        gitlabUrl: https://gitlab.svc.home.arpa
        certsSecretName: homelab-ca
        rbac:
          create: true
        runners:
          jobNamespace: gitlab-runner
          cache:
            secretName: gitlab-runner-s3-access
          secret: gitlab-runner-token-secret
          config: |-
            [[runners]]
              limit = 3
              request_concurrency = 2
              name = "kubernetes-runner"
              environment = [
                "GIT_SSL_CAINFO=/usr/local/share/ca-certificates/ca.crt",
                "SSL_CERT_FILE=/usr/local/share/ca-certificates/ca.crt",
                "REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/ca.crt",
                "NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/ca.crt",
                "BUILDKIT_HOST=tcp://buildkitd.buildkitd.svc.cluster.local:1234",
                "BUILDKIT_TLS_CACERT=/etc/buildkit/ca/ca.crt"
              ]
              pre_get_sources_script = """
              echo "Updating CA certificates..."
              # 1. Debian / Ubuntu / Alpine
              if command -v update-ca-certificates > /dev/null 2>&1; then
                echo "update-ca-certificates found, updating CA certificates..."
                update-ca-certificates --fresh
              # 2. RHEL / CentOS / Fedora
              elif command -v update-ca-trust > /dev/null 2>&1; then
                echo "update-ca-trust found, updating CA certificates..."
                update-ca-trust extract
              else
                echo "No built-in command found to update CA certificates, appending CA certificates to /etc/ssl/certs/ca-certificates.crt..."
                for cert in /usr/local/share/ca-certificates/*.crt; do
                  if [ -f "$cert" ]; then
                    cat "$cert" >> /etc/ssl/certs/ca-certificates.crt
                  fi
                done
              fi
              """

              [runners.kubernetes]
                privileged = false
                image = "alpine:latest"
                allowed_pull_policies = ["always", "if-not-present"]
                pull_policy = "if-not-present"

                cpu_request = "500m"
                cpu_limit = "2"
                memory_request = "1Gi"
                memory_limit = "4Gi"

              [[runners.kubernetes.volumes.secret]]
                name = "homelab-ca"
                mount_path = "/usr/local/share/ca-certificates"
                read_only = true

              [[runners.kubernetes.volumes.config_map]]
                name = "buildkitd-ca-trust"
                mount_path = "/etc/buildkit/ca"
                read_only = true
                [runners.kubernetes.volumes.config_map.items]
                  "ca.crt" = "ca.crt"

              [runners.cache]
                Type = "s3"
                Shared = true
                Path = "runner"
                [runners.cache.s3]
                  ServerAddress = "s3.storage.home.arpa"
                  BucketName = "gitlab-runner"
                  BucketLocation = "eu-west-1"
                  AuthenticationType = "access-key"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
