apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.20.1-rootless
          args:
            - --addr
            - unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --config
            - /etc/buildkit/buildkitd.toml
            - --oci-worker-no-process-sandbox
          ports:
            - name: tcp
              containerPort: 1234
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: buildkitd
              mountPath: /home/user/.local/share/buildkit
            - name: config
              mountPath: /etc/buildkit/buildkitd.toml
              subPath: buildkitd.toml
            - name: registry-ca
              mountPath: /etc/ssl/certs/registry-ca.crt
              subPath: ca.crt
      volumes:
        - name: buildkitd
          emptyDir: {}
        - name: config
          configMap:
            name: buildkitd-config
        - name: registry-ca
          secret:
            secretName: homelab-ca
