apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-ca
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homelab-ca
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ca.crt: "{{ .ca_crt }}"
        gitlab.svc.home.arpa.crt: "{{ .ca_crt }}"
        homelab-ca.crt: "{{ .ca_crt }}"
  data:
    - secretKey: ca_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-token-secret
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-token-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: ""
        runner-token: "{{ .runner_token }}"
  data:
    - secretKey: runner_token
      remoteRef:
        key: services/gitlab
        property: GITLAB_RUNNER_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-s3-access
  namespace: gitlab-runner
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: gitlab-runner-s3-access
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ .access_key }}"
        secretkey: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: services/gitlab
        property: GITLAB_S3_SECRET_ACCESS_KEY
