apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-mattermost-db-secret
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: mattermost-postgresql-app
  data:
    - match:
        secretKey: uri
        remoteRef:
          remoteKey: services/mattermost-db
          property: uri
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost-database-secret
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mattermost-database-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "{{ .uri }}?sslmode=disable"
  data:
    - secretKey: uri
      remoteRef:
        key: services/mattermost-db
        property: uri
