apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mattermost-postgresql-backup
  namespace: mattermost
spec:
  schedule: "0 0 1 * * *"
  backupOwnerReference: self
  cluster:
    name: mattermost-postgresql
