apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/grafana
  - ./resources/kube-prometheus-stack
  # - ./resources/dashboards
  - ./resources/kiali
  - ./resources/jaeger
  - ./resources/loki
  - ./resources/namespace.yaml
  - ./resources/prometheus-blackbox-exporter.yaml
