apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 2
  db:
    database: keycloak_db
    vendor: postgres
    host: psql.storage.home.arpa
    usernameSecret:
      name: keycloak-postgres-credentials
      key: postgres_username
    passwordSecret:
      name: keycloak-postgres-credentials
      key: postgres_password
  http:
    httpEnabled: true
  hostname:
    hostname: sso.svc.home.arpa
  ingress:
    enabled: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers

  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: fetch-provider-jar
            image: curlimages/curl:latest
            command:
              - sh
            args:
              - -ec
              - |
                mkdir -p /opt/keycloak/providers/ && \
                curl -fSLk -o /opt/keycloak/providers/keycloak-theme.jar "https://gitlab.svc.home.arpa/releases/web-apps/keycloak-theme/-/jobs/797/artifacts/raw/artifacts/keycloak-theme.jar?inline=false"
            volumeMounts:
              - name: provider-jar
                mountPath: /opt/keycloak/providers
        containers:
          - name: keycloak
            command: ["/opt/keycloak/bin/kc.sh"]
            args: ["start", "--optimized"]
            volumeMounts:
              - name: provider-jar
                mountPath: /opt/keycloak/providers
        volumes:
          - name: provider-jar
            emptyDir: {}
