apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtualservice-keycloak
  namespace: keycloak
spec:
  hosts:
    - sso.svc.home.arpa
  gateways:
    - gateway-keycloak
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: keycloak-service.keycloak.svc.cluster.local
            port:
              number: 8080
