apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: buildkitd-ca-trust
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  sources:
    - secret:
        name: buildkitd-ca
        key: tls.crt
  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: gitlab-runner
