apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-ca
  namespace: buildkitd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homelab-ca
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ca.crt: "{{ .ca_crt }}"
  data:
    - secretKey: ca_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.crt
