apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kallepan/homelab-manifests.git
    targetRevision: main
    path: applications/external-secrets-operator/charts/external-secrets
    helm:
      valuesObject:
        installCRDs: true
        serviceAccount:
          create: true
          name: external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
