apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: sonarqube
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    targetRevision: "2026.4.1"
    helm:
      releaseName: sonarqube
      valuesObject:
        community:
          enabled: true
        jdbcOverwrite:
          enabled: true
          jdbcUrl: "jdbc:postgresql://sonarqube-postgresql-rw.sonarqube.svc.cluster.local:5432/sonarqube"
          jdbcUsername: sonarqube
          jdbcSecretName: sonarqube-postgresql-app
          jdbcSecretPasswordKey: password
        postgresql:
          enabled: false
        persistence:
          enabled: true
          size: 5Gi
          storageClass: ceph-block
        caCerts:
          enabled: true
          secret: homelab-ca
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
