apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-drivers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ceph-csi-drivers
    repoURL: https://charts.rook.io/release
    targetRevision: "1.*.*"
    helm:
      releaseName: ceph-csi-drivers
      valuesObject: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
