apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup-credentials
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: postgres-backup-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .ACCESS_SECRET_KEY }}"
        ca.crt: "{{ .ca_crt }}"
        REGION: "eu-west-1"
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: services/postgres
        property: PG_BACKUPS_ACCESS_KEY
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: services/postgres
        property: PG_BACKUPS_SECRET_ACCESS_KEY
    - secretKey: ca_crt
      remoteRef:
        key: certificates/cert-manager-ca
        property: tls.crt
