apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: k6-operator
    repoURL: https://grafana.github.io/helm-charts
    targetRevision:  "4.*.*"
    helm:
      releaseName: k6-operator
      valuesObject: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k6-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
