apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-values.yaml
    target:
      kind: Application
      name: argocd
  - target:
      kind: Certificate
      name: argocd-tls
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: "argocd.lab.home.arpa"
