apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio-gateway
spec:
  listeners:
    - name: http
      protocol: HTTP
      hostname: "*.lab.home.arpa"
      port: 80
      allowedRoutes:
        namespaces:
          from: All
