apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: jaeger-operator
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.*.*
    helm:
      releaseName: jaeger-operator
      valuesObject:
        rbac:
          create: true
          clusterRole: true
        serviceAccount:
          create: true
          name: jaeger-operator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jaeger-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
