apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ./path-patch.yaml
    target:
      group: ""
      version: v1
      kind: ConfigMap
      name: local-path-config
      namespace: local-path-storage
