apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 0.24.0
    helm:
      releaseName: trust-manager
      valuesObject:
        crds:
          enabled: true
        app:
          trust:
            namespace: buildkitd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: trust-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
