{
 "title": "Gitlab Runner",
 "description": "Prometheus Metrics for Gitlab Runners",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(gitlab_runner_version_info,job)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(gitlab_runner_version_info,branch)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(gitlab_runner_version_info,architecture)"
    }
   },
   {
    "name": "go_version",
    "query": {
     "query": "label_values(gitlab_runner_version_info,go_version)"
    }
   },
   {
    "name": "built_at",
    "query": {
     "query": "label_values(gitlab_runner_version_info,built_at)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Build Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Version: ```${version}``` Architecture: ```${arch}``` Go: ```${go_version}``` Build at: ```${built_at}```"
   }
  },
  {
   "title": "Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (level) (rate(gitlab_runner_errors_total{job=~\"$job\"}[2m]))",
     "legendFormat": "{{instance}} {{level}}"
    }
   ]
  },
  {
   "title": "Failed Jobs Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (failure_reason, instance, runner) (rate(gitlab_runner_failed_jobs_total{job=~\"$job\"}[2m]))",
     "legendFormat": "{{failure_reason}} {{instance}} {{runner}}"
    }
   ]
  },
  {
   "title": "Configuration Loads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_configuration_loaded_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Loads Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_configuration_loading_error_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Saved",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_configuration_saved_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Saved Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_configuration_saving_error_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_worker_slots_number{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runner Concurrent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_concurrent{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Queuing Duration Exceeded Treshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_acceptable_job_queuing_duration_exceeded_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (executor_stage, instance) (gitlab_runner_jobs{job=~\"$job\"})",
     "legendFormat": "{{executor_stage}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance, runner, system_id) (rate(gitlab_runner_jobs_total{job=~\"$job\"}[2m]))",
     "legendFormat": "instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Job  Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Feeds Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (instance, runner, system_id, runner_name) (rate(gitlab_runner_worker_feeds_total{job=~\"$job\"}[2m]))",
     "legendFormat": "instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Feeds Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (instance, runner, system_id, runner_name) (rate(gitlab_runner_worker_feed_failures_total{job=~\"$job\"}[2m]))",
     "legendFormat": "instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Processing Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (instance, runner, system_id, runner_name, failure_type) (rate(gitlab_runner_worker_processing_failures_total{job=~\"$job\"}[2m]))",
     "legendFormat": "failure_type: {{failure_type}}, instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Health Check Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (instance, runner, system_id, runner_name) (rate(gitlab_runner_worker_health_check_failures_total{job=~\"$job\"}[2m]))",
     "legendFormat": "instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}, runner_name: {{runner_name}}"
    }
   ]
  },
  { "title": "Api and Autoscaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Api Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (endpoint, status, instance, runner, system_id) (rate(gitlab_runner_api_request_statuses_total{job=~\"$job\"}[2m]))",
     "legendFormat": "endpoint: {{endpoint}}, status: {{status}}, instance: {{instance}}, runner_id: {{runner}}; system_id: {{system_id}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Api Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Autoscaling Machine States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_states{job=~\"$job\"}",
     "legendFormat": "state: {{state}}, executor: {{executor}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Creation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Stopping Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_stopping_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_stopping_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_stopping_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_stopping_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Failed Creation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_failed_creation_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_failed_creation_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_failed_creation_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_failed_creation_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Removal Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_removal_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_removal_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_removal_duration_seconds_bucket{\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_autoscaling_machine_removal_duration_seconds_bucket{\n        job=~\"$job\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}