{
 "title": "Gitlab",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gitlab Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (feature_category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab Total Error Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5.+.+\"}[$__rate_interval])) by (feature_category, status)",
     "legendFormat": "{{feature_category}}: {{status}}"
    }
   ]
  },
  {
   "title": "Gitlab CI Job Queues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(gitlab_ci_queue_operations_total[$__rate_interval])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(gitlab_ruby_threads_running_threads) by (thread_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab DB Transaction Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(gitlab_database_transaction_seconds_count[$__rate_interval])) by (endpoint_id) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(gitlab_cache_misses_total[$__rate_interval])) by (endpoint_id) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } }
 ]
}