{
 "title": "Service Cluster Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Time per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(k8s_pod_cpu_time_seconds_total[$__rate_interval])) by (k8s_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Request Utilization per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_pod_cpu_request_utilization_ratio) by (k8s_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_pod_memory_request_utilization_ratio) by (k8s_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit Utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_pod_memory_limit_utilization_ratio) by (k8s_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_node_cpu_usage) by (k8s_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_node_memory_usage_bytes/(k8s_node_memory_available_bytes+k8s_node_memory_usage_bytes)) by (k8s_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Network Traffic by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(k8s_node_network_io_bytes_total[$__rate_interval])) by(k8s_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(k8s_node_filesystem_usage_bytes/k8s_node_filesystem_capacity_bytes) by (k8s_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime per Node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k8s_node_uptime_seconds_total) by (k8s_node_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}