apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: "3.*.*"
    helm:
      releaseName: kyverno
      valuesObject:
        crds:
          install: true
        config:
          enableDefaultRegistryMutation: false
        admissionController:
          replicas: 2
          podDisruptionBudget:
            enabled: true
            minAvailable: 1
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: admission-controller
          metricsService:
            create: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        backgroundController:
          metricsService:
            create: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        reportsController:
          metricsService:
            create: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        cleanupController:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: "3.*.*"
    helm:
      releaseName: kyverno-policies
      valuesObject:
        policyType: ValidatingPolicy
        podSecurityStandard: baseline
        validationFailureAction: Audit
        validationFailureActionByPolicy: {}
        validationFailureActionOverrides:
          all: []
        failurePolicy: Ignore
        validationAllowExistingViolations: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
