{
 "title": "Loki Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "log_severity",
    "label": "Log Severity",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Logs",
   "type": "timeseries",
   "description": "Number of Logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\", k8s_cluster=~\"$cluster\",log_severity=~\"$log_severity\"} |= \"$query\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Observed Logs",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_cluster=~\"$cluster\", k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\",log_severity=~\"$log_severity\"}"
    }
   ]
  },
  {
   "title": "Kubernetes Warnings",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"kube-events\"} |= \"$query\" | json | type = \"Warning\""
    }
   ]
  }
 ]
}