apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
metadata:
    name: "homelab-apps"
    namespace: "argocd"
spec:
    goTemplate: true
    goTemplateOptions: ["missingkey=error"]
    generators:
        - matrix:
            generators:
                # 1. Get all clusters
                - clusters:
                    selector:
                        matchExpressions:
                            - key: "type"
                              operator: In
                              values:
                                  - "management"
                                  - "service"

                # 2. Look for overlays that match the cluster type
                - git:
                    repoURL: "https://github.com/kallepan/homelab-manifests.git"
                    revision: "main"
                    directories:
                        - path: 'apps/*/overlays/{{ index .metadata.labels "type" }}'
                    requeueAfterSeconds: 600  # Poll every 10 minutes (default is 180 seconds)

    template:
        metadata:
            name: "{{ index .path.segments 1 }}-{{ .name }}"
            labels:
                app-type: "{{ index .path.segments 1 }}"
        spec:
            project: "default"
            source:
                repoURL: "https://github.com/kallepan/homelab-manifests.git"
                targetRevision: "main"
                path: "{{ .path.path }}"
            destination:
                server: "{{ .server }}"
                namespace: "{{ index .path.segments 1 }}"
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
                syncOptions:
                    - "CreateNamespace=true"

    syncPolicy:
        applicationsSync: "create-update"
