apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kallepan/homelab-manifests.git
    targetRevision: main
    path: applications/mattermost-operator/charts/mattermost-operator
    helm:
      releaseName: mattermost-operator
      valuesObject: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mattermost-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
