apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    name: keycloak
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
